#!/bin/sh
set -e

DB_HOST="${DB_HOST:-db}"
DB_PORT="${DB_PORT:-3306}"
DB_DATABASE="${DB_DATABASE:-purchase_entry}"
DB_USERNAME="${DB_USERNAME:-root}"
DB_PASSWORD="${DB_PASSWORD:-root}"
DB_CHARSET="${DB_CHARSET:-utf8mb4}"
DOCKER_DB_CONFIG="${DOCKER_DB_CONFIG:-/var/www/docker-config/database.php}"

export DB_HOST DB_PORT DB_DATABASE DB_USERNAME DB_PASSWORD DB_CHARSET DOCKER_DB_CONFIG

echo "[app] Waiting for MySQL at ${DB_HOST}:${DB_PORT}…"

i=0
until php -r '
$host = getenv("DB_HOST") ?: "db";
$port = getenv("DB_PORT") ?: "3306";
$db   = getenv("DB_DATABASE") ?: "purchase_entry";
$user = getenv("DB_USERNAME") ?: "root";
$pass = getenv("DB_PASSWORD") ?: "root";
new PDO(
    sprintf("mysql:host=%s;port=%s;dbname=%s;charset=utf8mb4", $host, $port, $db),
    $user,
    $pass,
    [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
);
' 2>/dev/null; do
  i=$((i + 1))
  if [ "$i" -ge 60 ]; then
    echo "[app] MySQL did not become ready in time." >&2
    exit 1
  fi
  sleep 1
done

echo "[app] MySQL is ready."

# Write DB config outside the bind-mounted project tree so host MAMP/XAMPP
# config/database.php is never overwritten or shadowed after Compose stops.
mkdir -p "$(dirname "$DOCKER_DB_CONFIG")"

esc() {
  printf "%s" "$1" | sed "s/'/\\\\'/g"
}

cat > "$DOCKER_DB_CONFIG" <<EOF
<?php

/**
 * Auto-generated by docker/entrypoint.sh (container-local; not in the git tree).
 */

return [
    'host' => '$(esc "$DB_HOST")',
    'port' => '$(esc "$DB_PORT")',
    'dbname' => '$(esc "$DB_DATABASE")',
    'username' => '$(esc "$DB_USERNAME")',
    'password' => '$(esc "$DB_PASSWORD")',
    'charset' => '$(esc "$DB_CHARSET")',
];
EOF

# Write APP_BASE_URL for Apache/mod_php (getenv from Compose is unreliable under Apache).
printf "<?php\n// generated by entrypoint — Docker domain-root base URL\nputenv('APP_BASE_URL=');\n\$_ENV['APP_BASE_URL'] = '';\n\$_SERVER['APP_BASE_URL'] = '';\n" \
  > /var/www/docker-config/app_base.php

# Auto-prepend so every request sees APP_BASE_URL="" (overrides config base_url).
cat > /usr/local/etc/php/conf.d/zz-docker-base-url.ini <<'INI'
auto_prepend_file=/var/www/docker-config/app_base.php
INI

echo "[app] Wrote ${DOCKER_DB_CONFIG}"

CONFIG_DIR="/var/www/html/config"
LOCK_FILE="${CONFIG_DIR}/installed.lock"
if [ ! -f "$LOCK_FILE" ]; then
  touch "$LOCK_FILE"
  echo "[app] Created config/installed.lock"
fi

chown -R www-data:www-data "$CONFIG_DIR" 2>/dev/null || true

exec "$@"
