<?php

/**
 * Database credentials (generated by the setup wizard).
 * Re-run setup by deleting config/installed.lock and visiting /install.
 */

return array (
  'host' => '127.0.0.1',
  'port' => '8889',
  'dbname' => 'purchase_entry',
  'username' => 'root',
  'password' => 'root',
  'charset' => 'utf8mb4',
);
